name: Execute Unit Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # Code Checkout from Github Repository
        uses: actions/checkout@v4

      - name: Setup .NET # Setup .Net environment to execute dotnet program
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Specify your .NET version

      - name: Restore dependencies # Restore nuget packages or dependencies
        run: dotnet restore
        
      - name: Build project
        run: dotnet build --configuration Debug

      - name: Execute Unit Tests
        run: |
          cd "/home/runner/work/LearnGitAction/LearnGitAction/LearnGitAction.Tests"
          dotnet test --no-build --verbosity normal
          
      - name: Print completion message # Print Success message if test runs successfully 
        if: success()
        run: echo "All tests executed successfully!"
