name: Output information workflow
on: workflow_dispatch
jobs:
  info: 
    runs-on: ubuntu-latest
    steps:
      - name: Output information # Print information about the workflow run
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "${{ toJSON(github) }}" # Check Github Expression Documentation for more information
